### ISSUE TITLE
[Bug/suggestion] Smart hoppers aren't so smart

### ISSUE THREAD

**Issue by frenchiveruti** [spdskatr/ProjectRimFactory#1]
The smart hopper have an intrinsic issue that when they get a stack count that's below the needed amount for a recipe (lets say the cooker need 10 meat and the Smart hopper has 9) the cooker can't cook, but the stack isn't empty either so the smart hopper doesn't bring any of the other stacks it has around.
In cases like meat where products are so varied unless you develop some monofactory of some kind of meat, this is a recurrent issue, and workarounds aren't useful on advanced stages of the game.
What I suggest is either reduce the cost and power draw of the smart hoppers, or make a "low threshold" like the inverse of the "stack max amount" where the user can say "ok, if this smart hopper has less than 15 hare meat, unforbid the stack so a pawn can come and move it and free the smart hopper".  
Thanks.

**Comment by spdskatr** [comment]
Closed.
