### ISSUE TITLE
Error on load and missing ui elements

### ISSUE THREAD

**Issue by h37001** [spdskatr/ProjectRimFactory#23]
When I load the core (no other mods) I get the error in the picture.
![rimfactory_error](https://user-images.githubusercontent.com/46360696/50667832-4b504a00-0f89-11e9-8e35-bd429edb0a0e.png)
 I can load a world and build the structures but, they don't have the ui elements.
![rimfactory_noui](https://user-images.githubusercontent.com/46360696/50667839-599e6600-0f89-11e9-8ad0-196b30c6c32f.png)

**Comment by spdskatr** [comment]
When did you get the mod? A very similar bug was fixed (I hope) in release 1.0.7.

**Comment by h37001** [comment]
I got the mod today and download the latest version.

**Comment by h37001** [comment]
I uninstalled the mod and re downloaded it and now it seems to work. Thanks for the help and sorry for the inconvenience. Looks like I probably installed the older version when reading the mod split notes.
