### ISSUE TITLE
Error with storage buildings

### ISSUE THREAD

**Issue by Kietriss** [spdskatr/ProjectRimFactory#28]
When changing over from your b19 release to the 1.0.7 release here, I received a wall of errors on initializing . if i ignore those errors it then loads fine but no storage building from this mod can ne clicked on. it also results in a error about attempting to assign a faction to the buildings if i use god-mode to attempt to build another one to work around this.
![2019-01-24](https://user-images.githubusercontent.com/7244264/51684276-af2ec700-1fb9-11e9-820a-0c661e6b8fb4.png)

**Comment by spdskatr** [comment]
Which mods did you load? You need to load PRF_Core.

**Comment by Kietriss** [comment]
I added all 4 of the ones in the release. When I get back to the computer tonight I will confirm load order. The buildings work as intended (for the ones built before updating from rimfactory to the new ones) they just cannot be selected to change any settings

**Comment by Kietriss** [comment]
Checked load order again and I feel like a fool. Problem is corrected
